1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [2]:
import numpy as np

lst=[]

length_of_lst=int(input('Enter the length of list: '))

for i in range(length_of_lst):
    user_input=float(input(f'Enter the {i}th element: '))
    lst.append(user_input)

print(f'The List is: {lst}')

arr=np.array(lst)
print(f'The 1d array is: {arr}')
print(arr.dtype)
print(type(arr))

The List is: [1.0, 2.0, 3.0, 4.0]
The 1d array is: [1. 2. 3. 4.]
float64
<class 'numpy.ndarray'>


2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

In [3]:
import numpy as np


arr=np.arange(2,11).reshape(3,3)

print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Write a Python program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [1]:
import numpy as np

vec=np.zeros(10)

print(vec)

vec[6]=11
print(vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [5]:
import numpy as np

arr=np.array([12 ,13 ,14, 15, 16, 17 ,18, 19, 20 ,21 ,22 ,23, 24 ,25,26 ,27 ,28 ,29, 30 ,31 ,32 ,33 ,34 ,35, 36, 37])

print(arr)

arr=np.flip(arr)

print(arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 1. 1. 1. 1.]]

In [6]:


import numpy as np

arr=np.full((5,5),1)

print(arr)

print()
arr=np.zeros((5,5),dtype=int)

arr[0,:]=1
arr[4,:]=1
arr[:,0]=1
arr[:,4]=1
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


6. Write a Python program to add a border (filled with 0's) around an existing array.
Expected Output:
Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 0. 0. 0. 0. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 0. 0. 0. 0.]]

In [7]:
import numpy as np

arr=np.full((3,3),1)

print(arr)

new_arr=np.zeros((5,5),dtype=int)

new_arr[1:4,1:4]=arr
print(new_arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]

In [8]:
import numpy as np

arr=np.zeros((8,8),dtype=int)

arr[1::2,::2]=1
arr[::2,1::2]=1

print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


8. Write a Python program to convert a list and tuple into arrays.
List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]

In [9]:

import numpy as np

lst=[1,2,3,4,5]
print(f'List is:{lst}')
print(type(lst))

arr=np.array(lst)
print(f'The array is:{arr}')
print(type(arr))

my_tuple=(1,2,3,4,5,6,7,8)
print(my_tuple)
print(type(my_tuple))

arra=np.array(my_tuple)
print(arra)
print(type(arra))

List is:[1, 2, 3, 4, 5]
<class 'list'>
The array is:[1 2 3 4 5]
<class 'numpy.ndarray'>
(1, 2, 3, 4, 5, 6, 7, 8)
<class 'tuple'>
[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


9. Write a Python program to append values to the end of an array.
Expected Output:
Original array:
[10, 20, 30]

After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [10]:
import numpy as np

arr=np.array([10,20,30])
print(arr)

new_arr=np.insert(arr,len(arr),[40,50,60,70,80,90])
print(new_arr)

[10 20 30]
[10 20 30 40 50 60 70 80 90]


10. Write a Python program to find the real and imaginary parts of an array of complex
numbers.
Expected Output:
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]
Real part of the array:
[ 1. 0.70710678]
Imaginary part of the array:
[ 0. 0.70710678]

In [1]:
import numpy as np

complex_array = np.array([1.00000000 + 0.j, 0.70710678 + 0.70710678j])


real_part = np.real(complex_array)
imaginary_part = np.imag(complex_array)


print("Original array:", complex_array)
print("Real part of the array:")
print(real_part)
print("Imaginary part of the array:")
print(imaginary_part)

Original array: [1.        +0.j         0.70710678+0.70710678j]
Real part of the array:
[1.         0.70710678]
Imaginary part of the array:
[0.         0.70710678]


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.
Expected Output:
Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24

In [16]:
import numpy as np

arr=np.arange(2,5)
print(arr)

print(f'The Length of the array is: {len(arr)}')
print(f'Length of one array element in bytes: {arr.itemsize}')
print(f'Total bytes consumed by the elements of the array:{arr.nbytes}')

[2 3 4]
The Length of the array is: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array:24


12. Write a Python program to find common values between two arrays.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]

In [ ]:
import numpy as np

array1=np.array([0,10,20,40,60])
array2=np.array([10,30,40])


print(f'Common values between two arrays: {np.intersect1d(array1,array2)}')


print(f'{array1[np.isin(array1,array2)]}')

Common values between two arrays: [10 40]
[10 40]


13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.
Expected Output:
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70, 90]
Set difference between two arrays:
[ 0 20 60 80]


In [20]:
import numpy as np

array1=np.array([0 ,10,20,40,60,80])
array2=np.array([10,30,40,50,70,90])
print(f'Set difference between two arrays:{np.setdiff1d(array1,array2)}')


Set difference between two arrays:[ 0 20 60 80]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]

In [22]:
import numpy as np

array1= np.array([ 0 ,10 ,20, 40 ,60 ,80])
array2=np.array([10, 30, 40, 50, 70])

print(f'Unique values that are in only one (not both) of the input arrays: {np.setxor1d(array1,array2)}')

Unique values that are in only one (not both) of the input arrays: [ 0 20 30 50 60 70 80]


15. Write a Python program compare two arrays using numpy.
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]

In [23]:
import numpy as np

array1=np.array([1,2])
array2=np.array([4,5])

print(array1>array2)
print(array1>=array2)
print(array1<array2)
print(array1<=array2)


[False False]
[False False]
[ True  True]
[ True  True]


16. Write a Python program to create a contiguous flattened array.
Original array:
[[10 20 30]
[20 40 50]]
New flattened array:
[10 20 30 20 40 50]

In [24]:
import numpy as np

arr=np.array([[10,20,30],
             [20,40,50]])

print(f'New flattened array: {arr.flatten()}')

New flattened array: [10 20 30 20 40 50]


17. Write a Python program to change the data type of an array.
Expected Output:
[[ 2 4 6]
[ 6 8 10]]
Data type of the array x is: int32
New Type: float64
[[ 2. 4. 6.]
[ 6. 8. 10.]]

In [29]:
import numpy as np

array1=np.array([[2,4,6],[6,8,10]],dtype=np.int32)
print(array1)
print(f'Data type of the array  is: {array1.dtype}')

array2=array1.astype(np.float64)
print(f'The new data type is:{array2.dtype}')
print(array2)

[[ 2  4  6]
 [ 6  8 10]]
Data type of the array  is: int32
The new data type is:float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


18. Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.
Expected Output:
[[ 1. 0. 0.]
[ 0. 1. 0.]
[ 0. 0. 1.]]

In [32]:
import numpy as np

array1=np.zeros((3,3),dtype=int)
print(array1)

array1[0:1,0:1]=1
array1[1:2,1:2]=1
array1[2:,2:]=1

print(array1)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


19. Write a Python program to create an array which looks like below array.
Expected Output:
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]
[ 1. 1. 1.]]

In [4]:
import numpy as np

array1=np.zeros((4,3),dtype=int)
print(array1)
for i in range(1,len(array1)):
    array1[i,:i] =1

# array[1:-1,:]
# array1[1,0]=1
# array1[2,0:2]=1
# array1[3,0:]=1

print(array1)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


20. Write a Python program to concatenate two 2-dimensional arrays.
Expected Output:
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]
Expected Output:
[[ 0 1 3 0 2 4]
[ 5 7 9 6 8 10]]

In [3]:
import numpy as np

array1=np.array([[0,1,3],[5,7,9]])
print(array1)
array2=np.array([[0,2,4],[6,8,10]])
print(array2)

arr=np.concatenate((array1,array2),axis=1)
print(arr)

[[0 1 3]
 [5 7 9]]
[[ 0  2  4]
 [ 6  8 10]]
[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


21. Write a Python program to make an array immutable (read-only).
Expected Output:
Test the array is read-only or not:
Try to change the value of the first element:
Traceback (most recent call last):
File "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", line 6, in
x[0] = 1
ValueError: assignment destination is read-only


In [ ]:
import numpy as np

arr=np.arange(2,8)
print(arr)

arr.flags.writeable=False

arr[0]=89
print(arr)


[2 3 4 5 6 7]
[89  3  4  5  6  7]


22. Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.
Expected Output:
Original array elements:
[[ 0 1 2 3]
[ 4 5 6 7]
[ 8 9 10 11]]
New array elements:
[[ 0 3 6 9]
[12 15 18 21]
[24 27 30 33]]


In [49]:
import numpy as np

arr=np.arange(0,12).reshape(3,4)

print(f'Original array elements: {arr}')

print(f'New array elements is:{arr*3}')


Original array elements: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New array elements is:[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


23. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:
Original array elements:
[[0 1]
[2 3]
[4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


In [53]:
import numpy as np

arr=np.arange(0,6).reshape(3,2)
print(arr)

new=arr.tolist()
print(f'Array to list:{new}')

[[0 1]
 [2 3]
 [4 5]]
Array to list:[[0, 1], [2, 3], [4, 5]]


24. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:
Original array elements:
[ 0.26153123 0.52760141 0.5718299 0.5927067 0.7831874 0.69746349
0.35399976 0.99469633 0.0694458 0.54711478]
Print array values with precision 3:
[ 0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


In [55]:
import numpy as np

arr=np.array([ 0.26153123, 0.52760141, 0.5718299 ,0.5927067, 0.7831874 ,0.69746349,
0.35399976 ,0.99469633, 0.0694458 ,0.54711478])

print(f'Original array elements: {arr}')

new_arr=np.round(arr,3)
print(f'Print array values with precision 3:{new_arr}')



Original array elements: [0.26153123 0.52760141 0.5718299  0.5927067  0.7831874  0.69746349
 0.35399976 0.99469633 0.0694458  0.54711478]
Print array values with precision 3:[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


25. Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array.
Expected Output:
Original array elements:
[ 1.60000000e-10 1.60000000e+00 1.20000000e+03 2.35000000e-01]
Print array values with precision 3:
[ 0. 1.6 1200. 0.235]


In [ ]:
import numpy as np

arr=np.array([1.60000000e-10 ,1.60000000e+00, 1.20000000e+03 ,2.35000000e-01])

print(arr)

np.set_printoptions(suppress=True,precision=3)

print(arr)

[   0.       1.6   1200.       0.235]


26. Write a Python program to how to add an extra column to an numpy array.
Expected Output:
[[ 10 20 30 100]
[ 40 50 60 200]]

In [74]:
import numpy as np

arr=np.array([[10,20,30,100],
           [40,50,60,200]])

new_col=np.array([[150],[250]])

result=np.column_stack((arr,new_col))
print(result)


[[ 10  20  30 100 150]
 [ 40  50  60 200 250]]


27. Write a Python program to remove specific elements in a numpy array.
Expected Output:
Original array:
[ 10 20 30 40 50 60 70 80 90 100]
Delete first, fourth and fifth elements:
[ 20 30 60 70 80 90 100]


In [79]:
import numpy as np

arr=np.arange(10,110,10)
print(arr)

remove_indices=[0,3,4]
result=np.delete(arr,remove_indices)
print(result)


[ 10  20  30  40  50  60  70  80  90 100]
[ 20  30  60  70  80  90 100]
